server:
  port: 8080

spring:
  application:
    name: wedrive

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wedrive?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: wedrive1!.
  jpa:
    hibernate:
      ddl-auto: update